# Use Docker-based container (instead of OpenVZ)
sudo: required

language: scala

scala:
  - 2.11.2

os:
 - linux

env:
  matrix:
  - BLAS_LIB=OpenBLAS

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/tmp
    - $HOME/onnx_models
    - .travis/OpenBLAS.cache

# Install the appropriate blas library (if any) and associated gonum software.
install:
  - source ${TRAVIS_BUILD_DIR}/.travis/$TRAVIS_OS_NAME/$BLAS_LIB/install.sh

before_script:
  - scripts/download_squeezenet.sh
  - scripts/download_resnet.sh

script:
  - sbt test
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
