# Use Docker-based container (instead of OpenVZ)
sudo: required

language: scala

addons:
  apt_packages:
    libopenblas-dev

scala:
  - 2.11.2

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/tmp
    - $HOME/onnx_models

before_script:
  - scripts/download_squeezenet.sh
  - scripts/download_resnet.sh

script:
  - sbt test
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
